const names = [
" Reliance Industries Limited " ,
" Tata Consultancy Services Limited " ,
" Hindustan Unilever Limited  " ,
" HDFC Bank Limited " ,
" Housing Development Finance Corporation Limited " ,
" Infosys Limited " ,
" Kotak Mahindra Bank Limited " ,
" Bharti Airtel Limited " ,
" ITC Limited " ,
" ICICI Bank Limited  " ,
" State Bank of India " ,
" Asian Paints Limited  " ,
" Avenue Supermarts Limited " ,
" Bajaj Finance Limited " ,
" Maruti Suzuki India Limited " ,
" HCL Technologies Limited  " ,
" Larsen & Toubro Limited " ,
" Wipro Limited " ,
" Axis Bank Limited " ,
" UltraTech Cement Limited  " ,
" HDFC Life Insurance Company Limited " ,
" Coal India Limited  " ,
" Oil & Natural Gas Corporation Limited " ,
" Sun Pharmaceutical Industries Limited " ,
" NTPC Limited  " ,
" Power Grid Corporation of India Limited " ,
" Titan Company Limited " ,
" Dabur India Limited " ,
" Indian Oil Corporation Limited  " ,
" Bajaj Finserv Limited " ,
" Pidilite Industries Limited " ,
" Bharat Petroleum Corporation Limited  " ,
" Hindustan Zinc Limited  " ,
" Britannia Industries Limited  " ,
" SBI Life Insurance Company Limited  " ,
" SHREE CEMENT LIMITED  " ,
" Bajaj Auto Limited  " ,
" SBI Cards and Payment Services Limited  " ,
" Tech Mahindra Limited " ,
" Godrej Consumer Products Limited  " ,
" Divi's Laboratories Limited " ,
" Dr. Reddy's Laboratories Limited  " ,
" ICICI Prudential Life Insurance Company Limited " ,
" Adani Ports and Special Economic Zone Limited " ,
" ICICI Lombard General Insurance Company Limited " ,
" Berger Paints (I) Limited " ,
" HDFC Asset Management Company Limited " ,
" GlaxoSmithKline Consumer Healthcare Limited " ,
" InterGlobe Aviation Limited " ,
" Siemens Limited " ,
" Eicher Motors Limited " ,
" Marico Limited  " ,
" Mahindra & Mahindra Limited " ,
" JSW Steel Limited " ,
" United Spirits Limited  " ,
" GAIL (India) Limited  " ,
" Cipla Limited " ,
" Colgate Palmolive (India) Limited " ,
" DLF Limited " ,
" Torrent Pharmaceuticals Limited " ,
" Procter & Gamble Hygiene and Health Care Limited  " ,
" Bandhan Bank Limited  " ,
" Biocon Limited  " ,
" Hero MotoCorp Limited " ,
" Grasim Industries Limited " ,
" Ambuja Cements Limited  " ,
" Tata Steel Limited  " ,
" Havells India Limited " ,
" Petronet LNG Limited  " ,
" Bharti Infratel Limited " ,
" Hindustan Petroleum Corporation Limited " ,
" Yes Bank Limited  " ,
" Alkem Laboratories Limited  " ,
" Bosch Limited " ,
" Cadila Healthcare Limited " ,
" Indraprastha Gas Limited  " ,
" Lupin Limited " ,
" UPL Limited " ,
" Info Edge (India) Limited " ,
" Larsen & Toubro Infotech Limited  " ,
" Bank of Baroda  " ,
" MRF Limited " ,
" Muthoot Finance Limited " ,
" NMDC Limited  " ,
" IndusInd Bank Limited " ,
" United Breweries Limited  " ,
" Power Finance Corporation Limited " ,
" Aurobindo Pharma Limited  " ,
" Vedanta Limited " ,
" Adani Green Energy Limited  " ,
" Whirlpool of India Limited  " ,
" Honeywell Automation India Limited  " ,
" Tata Motors Limited " ,
" Punjab National Bank  " ,
" Hindalco Industries Limited " ,
" GlaxoSmithKline Pharmaceuticals Limited " ,
" 3M India Limited  " ,
" Piramal Enterprises Limited " ,
" Kansai Nerolac Paints Limited " ,
" Adani Transmission Limited  " ,
" Container Corporation of India Limited  " ,
" NHPC Limited  " ,
" IDBI Bank Limited " ,
" Bajaj Holdings & Investment Limited " ,
" ABB India Limited " ,
" Jubilant Foodworks Limited  " ,
" Motherson Sumi Systems Limited  " ,
" Page Industries Limited " ,
" TATA CONSUMER PRODUCTS LIMITED  " ,
" The New India Assurance Company Limited " ,
" General Insurance Corporation of India  " ,
" Pfizer Limited  " ,
" ACC Limited " ,
" Bharat Electronics Limited  " ,
" Gillette India Limited  " ,
" IPCA Laboratories Limited " ,
" REC Limited " ,
" Hindustan Aeronautics Limited " ,
" Oracle Financial Services Software Limited  " ,
" Trent Limited " ,
" Rajesh Exports Limited  " ,
" PI Industries Limited " ,
" SRF Limited " ,
" Coromandel International Limited  " ,
" Gujarat Gas Limited " ,
" Apollo Hospitals Enterprise Limited " ,
" Bata India Limited  " ,
" Voltas Limited  " ,
" Indian Railway Catering And Tourism Corporation Limited " ,
" Balkrishna Industries Limited " ,
" Varun Beverages Limited " ,
" Nippon Life India Asset Management Limited  " ,
" Godrej Properties Limited " ,
" Adani Enterprises Limited " ,
" Shriram Transport Finance Company Limited " ,
" Relaxo Footwears Limited  " ,
" AU Small Finance Bank Limited " ,
" Sanofi India Limited  " ,
" TVS Motor Company Limited " ,
" Astral Poly Technik Limited " ,
" MindTree Limited  " ,
" Torrent Power Limited " ,
" Sundaram Finance Limited  " ,
" Aarti Industries Limited  " ,
" AIA Engineering Limited " ,
" Crompton Greaves Consumer Electricals Limited " ,
" Ashok Leyland Limited " ,
" MphasiS Limited " ,
" L&T Technology Services Limited " ,
" The Ramco Cements Limited " ,
" Oberoi Realty Limited " ,
" Cholamandalam Investment and Finance Company Limited  " ,
" Ajanta Pharma Limited " ,
" Zee Entertainment Enterprises Limited " ,
" LIC Housing Finance Limited " ,
" Atul Limited  " ,
" Aditya Birla Fashion and Retail Limited " ,
" Dr. Lal Path Labs Ltd.  " ,
" WABCO India Limited " ,
" Schaeffler India Limited  " ,
" Sun TV Network Limited  " ,
" Exide Industries Limited  " ,
" Polycab India Limited " ,
" Supreme Industries Limited  " ,
" Bharat Forge Limited  " ,
" Adani Power Limited " ,
" Bank of India " ,
" Max Financial Services Limited  " ,
" L&T Finance Holdings Limited  " ,
" IDFC First Bank Limited " ,
" Akzo Nobel India Limited  " ,
" Alembic Pharmaceuticals Limited " ,
" GMR Infrastructure Limited  " ,
" Castrol India Limited " ,
" Union Bank of India " ,
" Aditya Birla Capital Limited  " ,
" Gujarat State Petronet Limited  " ,
" Syngene International Limited " ,
" Godrej Industries Limited " ,
" Fortis Healthcare Limited " ,
" Steel Authority of India Limited  " ,
" Adani Gas Limited " ,
" City Union Bank Limited " ,
" Dalmia Bharat Limited " ,
" Canara Bank " ,
" Aavas Financiers Limited  " ,
" Sumitomo Chemical India Limited " ,
" Natco Pharma Limited  " ,
" Mahindra & Mahindra Financial Services Limited  " ,
" CRISIL Limited  " ,
" Cummins India Limited " ,
" Oil India Limited " ,
" Vodafone Idea Limited " ,
" ICICI Securities Limited  " ,
" The Indian Hotels Company Limited " ,
" Tata Power Company Limited  " ,
" Indian Overseas Bank  " ,
" Thermax Limited " ,
" Iifl Wealth Management Limited  " ,
" The Phoenix Mills Limited " ,
" Endurance Technologies Limited  " ,
" Jindal Steel & Power Limited  " ,
" Hatsun Agro Product Limited " ,
" Solar Industries India Limited  " ,
" The Federal Bank  Limited " ,
" Amara Raja Batteries Limited  " ,
" SJVN Limited  " ,
" Escorts Limited " ,
" Mahanagar Gas Limited " ,
" Manappuram Finance Limited  " ,
" Vinati Organics Limited " ,
" UCO Bank  " ,
" Emami Limited " ,
" Zydus Wellness Limited  " ,
" Motilal Oswal Financial Services Limited  " ,
" SKF India Limited " ,
" Bharat Heavy Electricals Limited  " ,
" JK Cement Limited " ,
" NIIT Technologies Limited " ,
" Godrej Agrovet Limited  " ,
" JSW Energy Limited  " ,
" Central Bank of India " ,
" RBL Bank Limited  " ,
" Hexaware Technologies Limited " ,
" TTK Prestige Limited  " ,
" Prestige Estates Projects Limited " ,
" Tata Communications Limited " ,
" V-Guard Industries Limited  " ,
" Metropolis Healthcare Limited " ,
" Security and Intelligence Services (India) Limited  " ,
" Minda Industries Limited  " ,
" Sheela Foam Limited " ,
" RITES Limited " ,
" Sundram Fasteners Limited " ,
" NLC India Limited " ,
" PVR Limited " ,
" Navin Fluorine International Limited  " ,
" Procter & Gamble Health Limited " ,
" AstraZeneca Pharma India Limited  " ,
" Kajaria Ceramics Limited  " ,
" Fine Organic Industries Limited " ,
" Johnson Controls - Hitachi Air Conditioning India Limited " ,
" Glenmark Pharmaceuticals Limited  " ,
" Timken India Limited  " ,
" Tata Chemicals Limited  " ,
" Indiabulls Ventures Limited " ,
" ITI Limited " ,
" Indiamart Intermesh Limited " ,
" Symphony Limited  " ,
" JM Financial Limited  " ,
" Cholamandalam Financial Holdings Limited  " ,
" National Aluminium Company Limited  " ,
" CESC Limited  " ,
" Deepak Nitrite Limited  " ,
" Blue Dart Express Limited " ,
" Bank of Maharashtra " ,
" Tube Investments of India Limited " ,
" Bombay Burmah Trading Corporation Limited " ,
" Eris Lifesciences Limited " ,
" Narayana Hrudayalaya Ltd. " ,
" Grindwell Norton Limited  " ,
" Shriram City Union Finance Limited  " ,
" Essel Propack Limited " ,
" Godfrey Phillips India Limited  " ,
" Finolex Industries Limited  " ,
" BASF India Limited  " ,
" CREDITACCESS GRAMEEN LIMITED  " ,
" Aster DM Healthcare Limited " ,
" KEC International Limited " ,
" Aegis Logistics Limited " ,
" Ujjivan Small Finance Bank Limited  " ,
" Apollo Tyres Limited  " ,
" Chambal Fertilizers & Chemicals Limited " ,
" Blue Star Limited " ,
" VST Industries Limited  " ,
" Ratnamani Metals & Tubes Limited  " ,
" Persistent Systems Limited  " ,
" Chalet Hotels Limited " ,
" Carborundum Universal Limited " ,
" Galaxy Surfactants Limited  " ,
" Orient Electric Limited " ,
" Dixon Technologies (India) Limited  " ,
" Linde India Limited " ,
" Indiabulls Housing Finance Limited  " ,
" JB Chemicals & Pharmaceuticals Limited  " ,
" Mangalore Refinery and Petrochemicals Limited " ,
" Avanti Feeds Limited  " ,
" Housing & Urban Development Corporation Limited " ,
" Jubilant Life Sciences Limited  " ,
" Future Retail Limited " ,
" Tata Elxsi Limited  " ,
" Amber Enterprises India Limited " ,
" Indian Energy Exchange Limited  " ,
" Asahi India Glass Limited " ,
" Engineers India Limited " ,
" Spandana Sphoorty Financial Limited " ,
" EIH Limited " ,
" Can Fin Homes Limited " ,
" KIOCL Limited " ,
" GMM Pfaudler Limited  " ,
" Granules India Limited  " ,
" Vardhman Textiles Limited " ,
" Edelweiss Financial Services Limited  " ,
" Ircon International Limited " ,
" Radico Khaitan Limited  " ,
" Cochin Shipyard Limited " ,
" Laurus Labs Limited " ,
" Nesco Limited " ,
" Rallis India Limited  " ,
" VIP Industries Limited  " ,
" Bharat Dynamics Limited " ,
" Jyothy Labs Limited " ,
" DCM Shriram Limited " ,
" Tata Investment Corporation Limited " ,
" Mishra Dhatu Nigam Limited  " ,
" FDC Limited " ,
" Century Textiles & Industries Limited " ,
" The India Cements Limited " ,
" HeidelbergCement India Limited  " ,
" CEAT Limited  " ,
" Birla Corporation Limited " ,
" GE Power India Limited  " ,
" ABB Power Products and Systems India Limited  " ,
" KRBL Limited  " ,
" Quess Corp Limited  " ,
" Gujarat Fluorochemicals Limited " ,
" Finolex Cables Limited  " ,
" APL Apollo Tubes Limited  " ,
" Sunteck Realty Limited  " ,
" Bajaj Electricals Limited " ,
" The Great Eastern Shipping Company Limited  " ,
" Sundaram Clayton Limited  " ,
" Cera Sanitaryware Limited " ,
" Capri Global Capital Limited  " ,
" DCB Bank Limited  " ,
" NBCC (India) Limited  " ,
" Gujarat Pipavav Port Limited  " ,
" Dilip Buildcon Limited  " ,
" Strides Pharma Science Limited  " ,
" MAS Financial Services Limited  " ,
" Kalpataru Power Transmission Limited  " ,
" Star Cement Limited " ,
" Omaxe Limited " ,
" Teamlease Services Limited  " ,
" KNR Constructions Limited " ,
" PNB Housing Finance Limited " ,
" INOX Leisure Limited  " ,
" TV18 Broadcast Limited  " ,
" Redington (India) Limited " ,
" Rail Vikas Nigam Limited  " ,
" Brigade Enterprises Limited " ,
" Indian Bank " ,
" Thyrocare Technologies Limited  " ,
" Techno Electric & Engineering Company Limited " ,
" Mahindra CIE Automotive Limited " ,
" V-Mart Retail Limited " ,
" Gulf Oil Lubricants India Limited " ,
" Sudarshan Chemical Industries Limited " ,
" Sterlite Technologies Limited " ,
" Affle (India) Limited " ,
" Suven Pharmaceuticals Limited " ,
" Sun Pharma Advanced Research Company Limited  " ,
" Cyient Limited  " ,
" Graphite India Limited  " ,
" Vaibhav Global Limited  " ,
" Century Plyboards (India) Limited " ,
" Swan Energy Limited " ,
" EID Parry India Limited " ,
" Lakshmi Machine Works Limited " ,
" Alkyl Amines Chemicals Limited  " ,
" MOIL Limited  " ,
" PNC Infratech Limited " ,
" KEI Industries Limited  " ,
" Lux Industries Limited  " ,
" Hathway Cable & Datacom Limited " ,
" Future Lifestyle Fashions Limited " ,
" IIFL Finance Limited  " ,
" IDFC Limited  " ,
" CCL Products (India) Limited  " ,
" Garware Technical Fibres Limited  " ,
" Maharashtra Scooters Limited  " ,
" K.P.R. Mill Limited " ,
" JK Lakshmi Cement Limited " ,
" Tasty Bite Eatables Limited " ,
" IndoStar Capital Finance Limited  " ,
" Balrampur Chini Mills Limited " ,
" Infibeam Avenues Limited  " ,
" Central Depository Services (India) Limited " ,
" Bharat Rasayan Limited  " ,
" Welspun India Limited " ,
" Responsive Industries Limited " ,
" Trident Limited " ,
" Kaveri Seed Company Limited " ,
" Caplin Point Laboratories Limited " ,
" Vakrangee Limited " ,
" TCI Express Limited " ,
" ICRA Limited  " ,
" Poly Medicure Limited " ,
" CSB Bank Limited  " ,
" TCNS Clothing Co. Limited " ,
" Shilpa Medicare Limited " ,
" Zensar Technologies Limited " ,
" Hindustan Copper Limited  " ,
" Bajaj Consumer Care Limited " ,
" Ingersoll Rand (India) Limited  " ,
" Indoco Remedies Limited " ,
" Network18 Media & Investments Limited " ,
" Sequent Scientific Limited  " ,
" Wockhardt Limited " ,
" Just Dial Limited " ,
" Firstsource Solutions Limited " ,
" Triveni Turbine Limited " ,
" BEML Limited  " ,
" Rain Industries Limited " ,
" IRB Infrastructure Developers Limited " ,
" HEG Limited " ,
" Mahindra Holidays & Resorts India Limited " ,
" Indiabulls Real Estate Limited  " ,
" MMTC Limited  " ,
" GE T&D India Limited  " ,
" Ujjivan Financial Services Limited  " ,
" Tata Steel Bsl Limited  " ,
" Federal-Mogul Goetze (India) Limited. " ,
" Gujarat Narmada Valley Fertilizers and Chemicals Limited  " ,
" Elgi Equipments Limited " ,
" Delta Corp Limited  " ,
" Shipping Corporation Of India Limited " ,
" Lemon Tree Hotels Limited " ,
" Sonata Software Limited " ,
" Varroc Engineering Limited  " ,
" BIRLASOFT LIMITED " ,
" Shoppers Stop Limited " ,
" Esab India Limited  " ,
" Vesuvius India Limited  " ,
" Max India Limited " ,
" Gujarat Alkalies and Chemicals Limited  " ,
" La Opala RG Limited " ,
" Mahindra Logistics Limited  " ,
" Welspun Corp Limited  " ,
" Fairchem Speciality Limited " ,
" Karur Vysya Bank Limited  " ,
" Greaves Cotton Limited  " ,
" JSW Holdings Limited  " ,
" Advanced Enzyme Technologies Limited  " ,
" Suprajit Engineering Limited  " ,
" Schneider Electric Infrastructure Limited " ,
" Garden Reach Shipbuilders & Engineers Limited " ,
" Rashtriya Chemicals and Fertilizers Limited " ,
" Dhanuka Agritech Limited  " ,
" Prism Johnson Limited " ,
" Nilkamal Limited  " ,
" Ksb Limited " ,
" Navneet Education Limited " ,
" Huhtamaki PPL Limited " ,
" Jindal Saw Limited  " ,
" Equitas Holdings Limited  " ,
" Gujarat State Fertilizers & Chemicals Limited " ,
" Den Networks Limited  " ,
" Transport Corporation of India Limited  " ,
" Raymond Limited " ,
" Allcargo Logistics Limited  " ,
" Orient Refractories Limited " ,
" Future Consumer Limited " ,
" VRL Logistics Limited " ,
" D.B.Corp Limited  " ,
" Balmer Lawrie & Company Limited " ,
" eClerx Services Limited " ,
" Jagran Prakashan Limited  " ,
" BSE Limited " ,
" JK Paper Limited  " ,
" Minda Corporation Limited " ,
" The Karnataka Bank Limited  " ,
" Maharashtra Seamless Limited  " ,
" Accelya Solutions India Limited " ,
" Sobha Limited " ,
" Kirloskar Oil Engines Limited " ,
" Supreme Petrochem Limited " ,
" Sterling And Wilson Solar Limited " ,
" Himadri Speciality Chemical Limited " ,
" Gujarat Ambuja Exports Limited  " ,
" Greenlam Industries Limited " ,
" Venky's (India) Limited " ,
" Jindal Stainless Limited  " ,
" Aarti Drugs Limited " ,
" PSP Projects Limited  " ,
" Prataap Snacks Limited  " ,
" NIIT Limited  " ,
" HFCL Limited  " ,
" Ashoka Buildcon Limited " ,
" Solara Active Pharma Sciences Limited " ,
" Arvind Fashions Limited " ,
" Ahluwalia Contracts (India) Limited " ,
" PTC India Limited " ,
" H.G. Infra Engineering Limited  " ,
" Prince Pipes And Fittings Limited " ,
" NCC Limited " ,
" Fertilizers and Chemicals Travancore Limited  " ,
" Tide Water Oil Company (India) Limited  " ,
" India Tourism Development Corporation Limited " ,
" Apar Industries Limited " ,
" Swaraj Engines Limited  " ,
" Unichem Laboratories Limited  " ,
" NOCIL Limited " ,
" Bannari Amman Sugars Limited  " ,
" Phillips Carbon Black Limited " ,
" IFB Industries Limited  " ,
" S H Kelkar and Company Limited  " ,
" Hinduja Global Solutions Limited  " ,
" Tata Coffee Limited " ,
" Bliss GVS Pharma Limited  " ,
" Suzlon Energy Limited " ,
" The South Indian Bank Limited " ,
" Gateway Distriparks Limited " ,
" Maithan Alloys Limited  " ,
" Praj Industries Limited " ,
" Gujarat Mineral Development Corporation Limited " ,
" R Systems International Limited " ,
" IOL Chemicals and Pharmaceuticals Limited " ,
" JK Tyre & Industries Limited  " ,
" UFLEX Limited " ,
" Greenply Industries Limited " ,
" TV Today Network Limited  " ,
" IIFL Securities Limited " ,
" Ramco Industries Limited  " ,
" Mahindra Lifespace Developers Limited " ,
" Heritage Foods Limited  " ,
" Sharda Cropchem Limited " ,
" KPIT Technologies Limited " ,
" Jtekt India Limited " ,
" Amrutanjan Health Care Limited  " ,
" CARE Ratings Limited  " ,
" Polyplex Corporation Limited  " ,
" Jamna Auto Industries Limited " ,
" Bombay Dyeing & Mfg Company Limited " ,
" Meghmani Organics Limited " ,
" Jindal Stainless (Hisar) Limited  " ,
" Agro Tech Foods Limited " ,
" Tata Metaliks Limited " ,
" Rupa & Company Limited  " ,
" Kiri Industries Limited " ,
" Orient Cement Limited " ,
" Kolte - Patil Developers Limited  " ,
" INEOS Styrolution India Limited " ,
" Tata Steel Long Products Limited  " ,
" Alembic Limited " ,
" Triveni Engineering & Industries Limited  " ,
" GFL Limited " ,
" Chennai Petroleum Corporation Limited " ,
" Jai Corp Limited  " ,
" Thomas Cook  (India)  Limited " ,
" National Fertilizers Limited  " ,
" Safari Industries (India) Limited " ,
" Shriram Pistons & Rings Limited " ,
" Shree Renuka Sugars Limited " ,
" Voltamp Transformers Limited  " ,
" Pilani Investment and Industries Corporation Limited  " ,
" Jindal Poly Films Limited " ,
" GHCL Limited  " ,
" DFM Foods Limited " ,
" West Coast Paper Mills Limited  " ,
" Dishman Carbogen Amcis Limited  " ,
" Savita Oil Technologies Limited " ,
" Hikal Limited " ,
" BF Investment Limited " ,
" Subros Limited  " ,
" Honda Siel Power Products Limited " ,
" Puravankara Limited " ,
" Balaji Amines Limited " ,
" Lumax Industries Limited  " ,
" Wheels India Limited  " ,
" Neogen Chemicals Limited  " ,
" Sandhar Technologies Limited  " ,
" The Tinplate Company of India Limited " ,
" Wonderla Holidays Limited " ,
" Hester Biosciences Limited  " ,
" Kewal Kiran Clothing Limited  " ,
" Punjab & Sind Bank  " ,
" Prime Focus Limited " ,
" Gabriel India Limited " ,
" Astec LifeSciences Limited  " ,
" Gujarat Industries Power Company Limited  " ,
" Dish TV India Limited " ,
" Newgen Software Technologies Limited  " ,
" PDS Multinational Fashions Limited  " ,
" Repco Home Finance Limited  " ,
" Majesco Limited " ,
" Intellect Design Arena Limited  " ,
" Tanla Solutions Limited " ,
" The Jammu & Kashmir Bank Limited  " ,
" Siyaram Silk Mills Limited  " ,
" Paisalo Digital Limited " ,
" Kirloskar Brothers Limited  " ,
" IFCI Limited  " ,
" Seamec Limited  " ,
" TVS Srichakra Limited " ,
" Mayur Uniquoters Ltd  " ,
" AGC Networks Limited  " ,
" Deepak Fertilizers and Petrochemicals Corporation Limited " ,
" Panacea Biotec Limited  " ,
" Sagar Cements Limited " ,
" Seshasayee Paper and Boards Limited " ,
" India Glycols Limited " ,
" JBM Auto Limited  " ,
" Healthcare Global Enterprises Limited " ,
" Satia Industries Limited  " ,
" Taj GVK Hotels & Resorts Limited  " ,
" Insecticides (India) Limited  " ,
" LT Foods Limited  " ,
" EIH Associated Hotels Limited " ,
" Matrimony.Com Limited " ,
" GOCL Corporation Limited  " ,
" Sundaram Finance Holdings Limited " ,
" Jindal Worldwide Limited  " ,
" Dollar Industries Limited " ,
" RattanIndia Power Limited " ,
" Tamil Nadu Newsprint & Papers Limited " ,
" Nava Bharat Ventures Limited  " ,
" DPSC Limited  " ,
" Hindustan Construction Company Limited  " ,
" Spencer's Retail Limited  " ,
" Welspun Enterprises Limited " ,
" Take Solutions Limited  " ,
" Himatsingka Seide Limited " ,
" Anant Raj Limited " ,
" Indian Hume Pipe Company Limited  " ,
" Automotive Axles Limited  " ,
" Igarashi Motors India Limited " ,
" JMC Projects (India)  Limited " ,
" V.S.T Tillers Tractors Limited  " ,
" Excel Industries Limited  " ,
" Foseco India Limited  " ,
" India Motor Parts and Accessories Limited " ,
" Kitex Garments Limited  " ,
" Entertainment Network (India) Limited " ,
" NRB Bearing Limited " ,
" Sasken Technologies Limited " ,
" J.Kumar Infraprojects Limited " ,
" Marksans Pharma Limited " ,
" GM Breweries Limited  " ,
" Time Technoplast Limited  " ,
" ANDHRA PAPER LIMITED  " ,
" The Orissa Minerals Development Company Limited " ,
" Oriental Carbon & Chemicals Limited " ,
" Mstc Limited  " ,
" Kalyani Steels Limited  " ,
" Steel Strips Wheels Limited " ,
" KCP Limited " ,
" Dhampur Sugar Mills Limited " ,
" Alok Industries Limited " ,
" BF Utilities Limited  " ,
" Prabhat Dairy Limited " ,
" Parag Milk Foods Limited  " ,
" Gallantt Ispat Limited  " ,
" GATI Limited  " ,
" Snowman Logistics Limited " ,
" Apex Frozen Foods Limited " ,
" Clariant Chemicals (India) Limited  " ,
" Cigniti Technologies Limited  " ,
" Texmaco Rail & Engineering Limited  " ,
" Nucleus Software Exports Limited  " ,
" Quick Heal Technologies Limited " ,
" Bodal Chemicals Limited " ,
" Srikalahasthi Pipes Limited " ,
" Music Broadcast Limited " ,
" NXTDIGITAL LIMITED  " ,
" Vindhya Telelinks Limited " ,
" ITD Cementation India Limited " ,
" LG Balakrishnan & Bros Limited  " ,
" Ashiana Housing Limited " ,
" Arvind Limited  " ,
" PTC India Financial Services Limited  " ,
" Sirca Paints India Limited  " ,
" Shankara Building Products Limited  " ,
" Shanthi Gears Limited " ,
" Shalby Limited  " ,
" Capacit'e Infraprojects Limited " ,
" Ramkrishna Forgings Limited " ,
" Religare Enterprises Limited  " ,
" Somany Home Innovation Limited  " ,
" Usha Martin Limited " ,
" Asian Granito India Limited " ,
" The Andhra Sugars Limited " ,
" Mold-Tek Packaging Limited  " ,
" Sadbhav Infrastructure Project Limited  " ,
" Bhansali Engineering Polymers Limited " ,
" Sterling Tools Limited  " ,
" Max Ventures and Industries Limited " ,
" Power Mech Projects Limited " ,
" Sanghi Industries Limited " ,
" Camlin Fine Sciences Limited  " ,
" HIL Limited " ,
" Indo Count Industries Limited " ,
" HBL Power Systems Limited " ,
" GTPL Hathway Limited  " ,
" Banco Products (I) Limited  " ,
" Sadbhav Engineering Limited " ,
" Rane Holdings Limited " ,
" Hindustan Oil Exploration Company Limited " ,
" Future Supply Chain Solutions Limited " ,
" Magma Fincorp Limited " ,
" Mastek Limited  " ,
" Oriental Aromatics Limited  " ,
" PC Jeweller Limited " ,
" VA Tech Wabag Limited " ,
" Astra Microwave Products Limited  " ,
" TTK Healthcare Limited  " ,
" Technocraft Industries (India) Limited  " ,
" Mirza International Limited " ,
" Kingfa Science & Technology (India) Limited " ,
" Sunflag Iron And Steel Company Limited  " ,
" Kirloskar Industries Limited  " ,
" SML Isuzu Limited " ,
" Geojit Financial Services Limited " ,
" Monnet Ispat & Energy Limited " ,
" PNB Gilts Limited " ,
" Morepen Laboratories Limited  " ,
" India Nippon Electricals Limited  " ,
" Sarda Energy & Minerals Limited " ,
" Kalyani Investment Company Limited  " ,
" Muthoot Capital Services Limited  " ,
" EBIXCASH WORLD MONEY INDIA LIMITED  " ,
" Jaiprakash Power Ventures Limited " ,
" Man Infraconstruction Limited " ,
" Inox Wind Limited " ,
" Dredging Corporation of India Limited " ,
" Kokuyo Camlin Limited " ,
" Cosmo Films Limited " ,
" Confidence Petroleum India Limited  " ,
" Olectra Greentech Limited " ,
" MM Forgings Limited " ,
" Electrosteel Castings Limited " ,
" Apcotex Industries Limited  " ,
" Mangalam Cement Limited " ,
" Zee Learn Limited " ,
" Repro India Limited " ,
" Texmaco Infrastructure & Holdings Limited " ,
" Future Enterprises Limited  " ,
" Filatex India Limited " ,
" Dalmia Bharat Sugar and Industries Limited  " ,
" HMT Limited " ,
" Somany Ceramics Limited " ,
" MPS Limited " ,
" Action Construction Equipment Limited " ,
" Renaissance Global Limited  " ,
" Punjab Chemicals & Crop Protection Limited  " ,
" Balaji Telefilms Limited  " ,
" Indiabulls Integrated Services Limited  " ,
" Mahanagar Telephone Nigam Limited " ,
" Centrum Capital Limited " ,
" Gufic Biosciences Limited " ,
" Lakshmi Vilas Bank Limited  " ,
" Godawari Power And Ispat limited  " ,
" The Investment Trust Of India Limited " ,
" Eveready Industries India Limited " ,
" NACL Industries Limited " ,
" Neuland Laboratories Limited  " ,
" Thirumalai Chemicals Limited  " ,
" AVT Natural Products Limited  " ,
" Genus Power Infrastructures Limited " ,
" Ganesha Ecosphere Limited " ,
" Wendt (India) Limited " ,
" GVK Power & Infrastructure Limited  " ,
" Xchanging Solutions Limited " ,
" Patel Engineering Limited " ,
" Tata Teleservices (Maharashtra) Limited " ,
" Greenpanel Industries Limited " ,
" Reliance Power Limited  " ,
" Arman Financial Services Limited  " ,
" The Sandesh Limited " ,
" N. B. I. Industrial Finance Company Limited " ,
" Pricol Limited  " ,
" BOROSIL RENEWABLES LIMITED  " ,
" Surya Roshni Limited  " ,
" ADF Foods Limited " ,
" Saregama India Limited  " ,
" Lumax Auto Technologies Limited " ,
" Shree Digvijay Cement Co.Ltd  " ,
" Prakash Industries Limited  " ,
" Aptech Limited  " ,
" Fiem Industries Limited " ,
" Sharda Motor Industries Limited " ,
" The Anup Engineering Limited  " ,
" Bhageria Industries Limited " ,
" Cantabil Retail India Limited " ,
" Asian Hotels (West) Limited " ,
" Unitech Limited " ,
" IFGL Refractories Limited " ,
" Centum Electronics Limited  " ,
" Thangamayil Jewellery Limited " ,
" Satin Creditcare Network Limited  " ,
" Vadilal Industries Limited  " ,
" Bharat Bijlee Limited " ,
" Sutlej Textiles and Industries Limited  " ,
" Apollo Pipes Limited  " ,
" Zota Health Care LImited  " ,
" GIC Housing Finance Limited " ,
" CG Power and Industrial Solutions Limited " ,
" CESC Ventures Limited " ,
" Sreeleathers Limited  " ,
" Dwarikesh Sugar Industries Limited  " ,
" Indraprastha Medical Corporation Limited  " ,
" Reliance Industrial Infrastructure Limited  " ,
" Oriental Hotels Limited " ,
" GTL Infrastructure Limited  " ,
" NELCO Limited " ,
" Orient Paper & Industries Limited " ,
" Atul Auto Limited " ,
" Control Print Limited " ,
" GNA Axles Limited " ,
" Ambika Cotton Mills Limited " ,
" Nalwa Sons Investments Limited  " ,
" Bajaj Hindusthan Sugar Limited  " ,
" Indian Metals & Ferro Alloys Limited  " ,
" Summit Securities Limited " ,
" Emami Paper Mills Limited " ,
" BLS International Services Limited  " ,
" Vardhman Holdings Limited " ,
" Dynamatic Technologies Limited  " ,
" Tejas Networks Limited  " ,
" Indo Rama Synthetics (India) Limited  " ,
" IG Petrochemicals Limited " ,
" Plastiblends India Limited  " ,
" HSIL Limited  " ,
" 5Paisa Capital Limited  " ,
" Mangalore Chemicals & Fertilizers Limited " ,
" Titagarh Wagons Limited " ,
" Associated Alcohols & Breweries Ltd.  " ,
" RattanIndia Infrastructure Limited  " ,
" RPG Life Sciences Limited " ,
" Hindustan Media Ventures Limited  " ,
" Bharat Road Network Limited " ,
" Monte Carlo Fashions Limited  " ,
" Rane Brake Lining Limited " ,
" GKW Limited " ,
" Deccan Cements Limited  " ,
" Tourism Finance Corporation of India Limited  " ,
" Suven Life Sciences Limited " ,
" Dewan Housing Finance Corporation Limited " ,
" Uniphos Enterprises Limited " ,
" Rico Auto Industries Limited  " ,
" Universal Cables Limited  " ,
" Navkar Corporation Limited  " ,
" Reliance Infrastructure Limited " ,
" Shalimar Paints Limited " ,
" Nelcast Limited " ,
" TD Power Systems Limited  " ,
" Kesoram Industries Limited  " ,
" Century Enka Limited  " ,
" Zuari Agro Chemicals Limited  " ,
" Lincoln Pharmaceuticals Limited " ,
" Munjal Auto Industries Limited  " ,
" Nath Bio-Genes (India) Limited  " ,
" Jaiprakash Associates Limited " ,
" N R Agarwal Industries Limited  " ,
" Ador Welding Limited  " ,
" DIC India Limited " ,
" Kuantum Papers Limited  " ,
" Hindusthan National Glass & Industries Limited  " ,
" Gandhi Special Tubes Limited  " ,
" NCL Industries Limited  " ,
" Harita Seating Systems Limited  " ,
" Globus Spirits Limited  " ,
" Alicon Castalloy Limited  " ,
" Datamatics Global Services Limited  " ,
" Vishwaraj Sugar Industries Limited  " ,
" Southern Petrochemicals Industries Corporation  Limited " ,
" Arvind SmartSpaces Limited  " ,
" Pearl Global Industries Limited " ,
" Anjani Portland Cement Limited  " ,
" Avadh Sugar & Energy Limited  " ,
" Precision Camshafts Limited " ,
" Man Industries (India) Limited  " ,
" HT Media Limited  " ,
" Munjal Showa Limited  " ,
" Zodiac Clothing Company Limited " ,
" Gravita India Limited " ,
" Ajmera Realty & Infra India Limited " ,
" MEP Infrastructure Developers Limited " ,
" Vidhi Specialty Food Ingredients Limited  " ,
" SMS Pharmaceuticals Limited " ,
" Shree Pushkar Chemicals & Fertilisers Limited " ,
" GIR Natureview Resorts Limited  " ,
" Ramco Systems Limited " ,
" Shriram EPC Limited " ,
" Career Point Limited  " ,
" Tamilnadu PetroProducts Limited " ,
" IFB Agro Industries Limited " ,
" Marine Electricals (India) Limited  " ,
" Themis Medicare Limited " ,
" Nectar Lifesciences Limited " ,
" UFO Moviez India Limited  " ,
" Jay Bharat Maruti Limited " ,
" Shakti Pumps (India) Limited  " ,
" D-Link (India) Limited  " ,
" Vardhman Acrylics Limited " ,
" Pennar Industries Limited " ,
" Visaka Industries Limited " ,
" Linc Pen & Plastics Limited " ,
" Cerebra Integrated Technologies Limited " ,
" Elecon Engineering Company Limited  " ,
" 63 moons technologies limited " ,
" The Ruby Mills Limited  " ,
" 3i Infotech Limited " ,
" Maheshwari Logistics Limited  " ,
" Everest Industries Limited  " ,
" Mahindra EPC Irrigation Limited " ,
" Dhanlaxmi Bank Limited  " ,
" Ester Industries Limited  " ,
" Goldiam International Limited " ,
" Sanghvi Movers Limited  " ,
" HLV LIMITED " ,
" PPAP Automotive Limited " ,
" Madras Fertilizers Limited  " ,
" Chembond Chemicals Ltd  " ,
" Uttam Sugar Mills Limited " ,
" Oswal Chemicals & Fertilizers Limited " ,
" Hind Rectifiers Limited " ,
" Skipper Limited " ,
" Som Distilleries & Breweries Limited  " ,
" Marathon Nextgen Realty Limited " ,
" Tilaknagar Industries Limited " ,
" Cupid Limited " ,
" Mukand Limited  " ,
" The State Trading Corporation of India Limited  " ,
" Sastasundar Ventures Limited  " ,
" PTL Enterprises Limited " ,
" Madhav Copper Limited " ,
" Jai Balaji Industries Limited " ,
" Albert David Limited  " ,
" SREI Infrastructure Finance Limited " ,
" Euro India Fresh Foods Limited  " ,
" Artemis Medicare Services Limited " ,
" Reliance Communications Limited " ,
" Nagarjuna Fertilizers and Chemicals Limited " ,
" Manaksia Limited  " ,
" Ashapura Minechem Limited " ,
" Allsec Technologies Limited " ,
" V2 Retail Limited " ,
" Zen Technologies Limited  " ,
" Subex Limited " ,
" RSWM Limited  " ,
" Manali Petrochemicals Limited " ,
" Menon Bearings Limited  " ,
" Jayant Agro Organics Limited  " ,
" Liberty Shoes Limited " ,
" Butterfly Gandhimathi Appliances Limited  " ,
" Panama Petrochem Limited  " ,
" Deep Industries Limited " ,
" Rane (Madras) Limited " ,
" Shree Rama Newsprint Limited  " ,
" Zee Media Corporation Limited " ,
" Arshiya Limited " ,
" Vardhman Special Steels Limited " ,
" Orbit Exports Limited " ,
" Raj Television Network Limited  " ,
" New Delhi Television Limited  " ,
" Jain Irrigation Systems Limited " ,
" Fineotex Chemical Limited " ,
" Hercules Hoists Limited " ,
" Dhunseri Ventures Limited " ,
" Hindustan Composites Limited  " ,
" Indo-National Limited " ,
" Ucal Fuel Systems Limited " ,
" DCW Limited " ,
" Gayatri Projects Limited  " ,
" Osia Hyper Retail Limited " ,
" InfoBeans Technologies Limited  " ,
" Karda Constructions Limited " ,
" Gallantt Metal Limited  " ,
" Precision Wires India Limited " ,
" Nitin Spinners Limited  " ,
" Thejo Engineering Limited " ,
" GP Petroleums Limited " ,
" Jet Airways (India) Limited " ,
" Pokarna Limited " ,
" S. P. Apparels Limited  " ,
" MSP Steel & Power Limited " ,
" Akash Infra-Projects Limited  " ,
" 3rd Rock Multimedia Limited " ,
" Alankit Limited " ,
" Kaya Limited  " ,
" Gujarat Apollo Industries Limited " ,
" Vipul Limited " ,
" BGR Energy Systems Limited  " ,
" Oricon Enterprises Limited  " ,
" Crest Ventures Limited  " ,
" OnMobile Global Limited " ,
" MMP Industries Limited  " ,
" Asian Hotels (East) Limited " ,
" KCP Sugar and Industries Corporation Limited  " ,
" The Hi-Tech Gears Limited " ,
" Brightcom Group Limited " ,
" Expleo Solutions Limited  " ,
" Ramky Infrastructure Limited  " ,
" TCPL Packaging Limited  " ,
" Madhya Bharat Agro Products Limited " ,
" Sangam (India) Limited  " ,
" Chemfab Alkalis Limited " ,
" Gokaldas Exports Limited  " ,
" Advani Hotels & Resorts (India) Limited " ,
" HPL Electric & Power Limited  " ,
" Khadim India Limited  " ,
" Orient Abrasives Limited  " ,
" Optiemus Infracom Limited " ,
" KDDL Limited  " ,
" TIPS Industries Limited " ,
" Saksoft Limited " ,
" S Chand And Company Limited " ,
" Rossell India Limited " ,
" Shemaroo Entertainment Limited  " ,
" Kabra Extrusion Technik Limited " ,
" D. P. Abhushan Limited  " ,
" SORIL Infra Resources Limited " ,
" Gujarat Sidhee Cement Limited " ,
" Tribhovandas Bhimji Zaveri Limited  " ,
" OM Metals Infraprojects Limited " ,
" Asian Hotels (North) Limited  " ,
" Jindal Drilling And Industries Limited  " ,
" Shrenik Limited " ,
" Vimta Labs Limited  " ,
" Industrial Investment Trust Limited " ,
" Vascon Engineers Limited  " ,
" Dynemic Products Limited  " ,
" Silver Touch Technologies Limited " ,
" Krebs Biochemicals and Industries Limited " ,
" Pioneer Distilleries Limited  " ,
" Sanginita Chemicals Limited " ,
" Swelect Energy Systems Limited  " ,
" Kilitch Drugs (India) Limited " ,
" Sree Rayalaseema Hi-Strength Hypo Limited " ,
" Astron Paper & Board Mill Limited " ,
" Banswara Syntex Limited " ,
" VLS Finance Limited " ,
" Jayaswal Neco Industries Limited  " ,
" AksharChem India Limited  " ,
" Kamdhenu Limited  " ,
" D B Realty Limited  " ,
" Everest Kanto Cylinder Limited  " ,
" Poddar Pigments Limited " ,
" Prozone Intu Properties Limited " ,
" The Ugar Sugar Works Limited  " ,
" Krishana Phoschem Limited " ,
" HCL Infosystems Limited " ,
" Ponni Sugars (Erode) Limited  " ,
" Airan Limited " ,
" Dangee Dums Limited " ,
" Jubilant Industries Limited " ,
" Jash Engineering Limited  " ,
" Paramount Communications Limited  " ,
" Emkay Taps and Cutting Tools Limited  " ,
" Reliance Capital Limited  " ,
" Goa Carbon Limited  " ,
" Praxis Home Retail Limited  " ,
" DRS Dilip Roadlines Limited " ,
" Royal Orchid Hotels Limited " ,
" Gokul Agro Resources Limited  " ,
" Gokul Refoils and Solvent Limited " ,
" Reliance Naval and Engineering Limited  " ,
" Shiva Texyarn Limited " ,
" Lasa Supergenerics Limited  " ,
" Eimco Elecon (India) Limited  " ,
" Electrotherm (India) Limited  " ,
" Mittal Life Style Limited " ,
" Star Paper Mills Limited  " ,
" Kopran Limited  " ,
" Bannari Amman Spinning Mills Limited  " ,
" Sarla Performance Fibers Limited  " ,
" Orient Green Power Company Limited  " ,
" Aditya Birla Money Limited  " ,
" Rushil Decor Limited  " ,
" Donear Industries Limited " ,
" Essar Shipping Limited  " ,
" Speciality Restaurants Limited  " ,
" AXISCADES Engineering Technologies Limited  " ,
" B. L. Kashyap and Sons Limited  " ,
" Pudumjee Paper Products Limited " ,
" Simplex Infrastructures Limited " ,
" Seya Industries Limited " ,
" Kanoria Chemicals & Industries Limited  " ,
" Kothari Products Limited  " ,
" Apollo Sindoori Hotels Limited  " ,
" Selan Exploration Technology Limited  " ,
" Inventure Growth & Securities Limited " ,
" Poddar Housing and Development Limited  " ,
" Gulshan Polyols Limited " ,
" TIL Limited " ,
" TCI Developers Limited  " ,
" TVS Electronics Limited " ,
" Nila Infrastructures Limited  " ,
" Mazda Limited " ,
" Harrisons  Malayalam Limited  " ,
" Ind-Swift Laboratories Limited  " ,
" Birla Cable Limited " ,
" Salasar Techno Engineering Limited  " ,
" Indian Terrain Fashions Limited " ,
" Walchandnagar Industries Limited  " ,
" Mold-Tek Technologies Limited " ,
" The United Nilgiri Tea Estates Company Limited  " ,
" Shivam Autotech Limited " ,
" Salzer Electronics Limited  " ,
" STEEL EXCHANGE INDIA LIMITED  " ,
" Bombay Rayon Fashions Limited " ,
" Apollo Micro Systems Limited  " ,
" Nahar Spinning Mills Limited  " ,
" Baba Agro Food Limited  " ,
" Magadh Sugar & Energy Limited " ,
" Aurionpro Solutions Limited " ,
" GeeCee Ventures Limited " ,
" MIRC Electronics Limited  " ,
" Creative Peripherals and Distribution Limited " ,
" Jaypee Infratech Limited  " ,
" Asahi Songwon Colors Limited  " ,
" 20 Microns Limited  " ,
" Mahamaya Steel Industries Limited " ,
" Bhartiya International Limited  " ,
" Shreyans Industries Limited " ,
" Jayshree Tea & Industries Limited " ,
" Mawana Sugars Limited " ,
" Rane Engine Valve Limited " ,
" Nitco Limited " ,
" Revathi Equipment Limited " ,
" Ganesh Housing Corporation Limited  " ,
" Sakthi Sugars Limited " ,
" Talbros Automotive Components Limited " ,
" Arihant Superstructures Limited " ,
" Mangalam Global Enterprise Limited  " ,
" Nahar Capital and Financial Services Limited  " ,
" Sintercom India Limited " ,
" Bombay Super Hybrid Seeds Limited " ,
" Shreyas Shipping & Logistics Limited  " ,
" Kakatiya Cement Sugar & Industries Limited  " ,
" SIL Investments Limited " ,
" Hitech Corporation Limited  " ,
" Ruchira Papers Limited  " ,
" Capital Trust Limited " ,
" Smartlink Holdings Limited  " ,
" RKEC Projects Limited " ,
" Jocil Limited " ,
" GRP Limited " ,
" Aban Offshore Limited " ,
" SKM Egg Products Export (India) Limited " ,
" Eros International Media Limited  " ,
" Genus Paper & Boards Limited  " ,
" Zuari Global Limited  " ,
" Inspirisys Solutions Limited  " ,
" Maha Rashtra Apex Corporation Limited " ,
" Spectrum Electrical Industries Limited  " ,
" Vikas Multicorp Limited " ,
" Alphageo (India) Limited  " ,
" Wealth First Portfolio Managers Limited " ,
" Vishnu Chemicals Limited  " ,
" Hi-Tech Pipes Limited " ,
" AYM Syntex Limited  " ,
" Cybertech Systems And Software Limited  " ,
" Dhunseri Tea & Industries Limited " ,
" Emami Realty Limited  " ,
" Orient Bell Limited " ,
" Indo Tech Transformers Limited  " ,
" Emmbi Industries Limited  " ,
" Sanwaria Consumer Limited " ,
" Prime Securities Limited  " ,
" Kapston Facilities Management Limited " ,
" Vinyl Chemicals (India) Limited " ,
" Genesys International Corporation Limited " ,
" Uniply Industries Limited " ,
" Setco Automotive Limited  " ,
" Innovana Thinklabs Limited  " ,
" Sakar Healthcare Limited  " ,
" Dhunseri Investments Limited  " ,
" Umang Dairies Limited " ,
" Balaxi Ventures Limited " ,
" PIL ITALICA LIFESTYLE LIMITED " ,
" Consolidated Finvest & Holdings Limited " ,
" Transformers And Rectifiers (India) Limited " ,
" Nandan Denim Limited  " ,
" Commercial Engineers & Body Builders Co Limited " ,
" Nahar Industrial Enterprises Limited  " ,
" Stel Holdings Limited " ,
" De Nora India Limited " ,
" Kothari Sugars And Chemicals Limited  " ,
" Sakuma Exports Limited  " ,
" D P Wires Limited " ,
" Trigyn Technologies Limited " ,
" R.P.P. Infra Projects Limited " ,
" Vertoz Advertising Limited  " ,
" Onward Technologies Limited " ,
" JAKHARIA FABRIC LIMITED " ,
" B&B Triplewall Containers Limited " ,
" Kellton Tech Solutions Limited  " ,
" Peninsula Land Limited  " ,
" Xelpmoc Design And Tech Limited " ,
" MRO-TEK Realty Limited  " ,
" Pitti Engineering Limited " ,
" Aspinwall and Company Limited " ,
" Modi Rubber Limited " ,
" Superhouse Limited  " ,
" Housing Development and Infrastructure Limited  " ,
" Premier Explosives Limited  " ,
" DiGiSPICE Technologies Limited  " ,
" Uttam Value Steels Limited  " ,
" Iris Clothings Limited  " ,
" Coral India Finance & Housing Limited " ,
" Worth Peripherals Limited " ,
" SPL Industries Limited  " ,
" Bhagyanagar Properties Limited  " ,
" Nahar Poly Films Limited  " ,
" Sagardeep Alloys Limited  " ,
" Hindustan Motors Limited  " ,
" Emkay Global Financial Services Limited " ,
" Kothari Petrochemicals Limited  " ,
" SKIL Infrastructure Limited " ,
" Sundaram Brake Linings Limited  " ,
" Uttam Galva Steels Limited  " ,
" Allied Digital Services Limited " ,
" T T Limited " ,
" JBF Industries Limited  " ,
" Orient Press Limited  " ,
" Shiv Aum Steels Limited " ,
" Shree Vasu Logistics Limited  " ,
" Mahickra Chemicals Limited  " ,
" Standard Industries Limited " ,
" Windsor Machines Limited  " ,
" Saketh Exim Limited " ,
" Vivimed Labs Limited  " ,
" Wonder Fibromats Limited  " ,
" IL&FS Investment Managers Limited " ,
" Amj Land Holdings Limited " ,
" Ahlada Engineers Limited  " ,
" Parin Furniture Limited " ,
" Kritika Wires Limited " ,
" Lovable Lingerie Limited  " ,
" Pashupati Cotspin Limited " ,
" BDR Buildcon Limited  " ,
" Goodluck India Limited  " ,
" K.M.Sugar Mills Limited " ,
" Universus Photo Imagings Limited  " ,
" Adhunik Industries Limited  " ,
" Ruchi Soya Industries Limited " ,
" Nitiraj Engineers Limited " ,
" Hubtown Limited " ,
" TRF Limited " ,
" Tokyo Plast International Limited " ,
" Rajshree Polypack Limited " ,
" Ansal Properties & Infrastructure Limited " ,
" Elgi Rubber Company Limited " ,
" A2Z Infra Engineering Limited " ,
" Uravi T and Wedge Lamps Limited " ,
" Veto Switchgears And Cables Limited " ,
" Shree Ram Proteins Limited  " ,
" Jullundur Motor Agency (Delhi) Limited  " ,
" Libas Designs Limited " ,
" Parsvnath Developers Limited  " ,
" Panache Digilife Limited  " ,
" SMS Lifesciences India Limited  " ,
" BPL Limited " ,
" Oswal Agro Mills Limited  " ,
" Suumaya Lifestyle Limited " ,
" MITCON Consultancy & Engineering Services Limited " ,
" Cineline India Limited  " ,
" Refex Industries Limited  " ,
" Ice Make Refrigeration Limited  " ,
" Aries Agro Limited  " ,
" Geekay Wires Limited  " ,
" Compuage Infocom Limited  " ,
" Welspun Investments and Commercials Limited " ,
" Kirloskar Electric Company Limited  " ,
" Touchwood Entertainment Limited " ,
" Urja Global Limited " ,
" PG Electroplast Limited " ,
" Bharat Wire Ropes Limited " ,
" MT Educare Limited  " ,
" Global Vectra Helicorp Limited  " ,
" Opto Circuits (India) Limited " ,
" Future Market Networks Limited  " ,
" Noida Toll Bridge Company Limited " ,
" Rana Sugars Limited " ,
" TPL Plastech Limited  " ,
" Aksh Optifibre Limited  " ,
" Mangalam Drugs And Organics Limited " ,
" Signet Industries Limited " ,
" Siti Networks Limited " ,
" Lotus Eye Hospital and Institute Limited  " ,
" Prakash Pipes Limited " ,
" Arrow Greentech Limited " ,
" Tara Chand Logistic Solutions Limited " ,
" The Motor & General Finance Limited " ,
" Ujaas Energy Limited  " ,
" Rudrabhishek Enterprises Limited  " ,
" Andhra Cements Limited  " ,
" Videocon Industries Limited " ,
" M.R. Organisation Limited " ,
" Jagsonpal Pharmaceuticals Limited " ,
" Bhagyanagar India Limited " ,
" Agarwal Industrial Corporation Limited  " ,
" Ballarpur Industries Limited  " ,
" Bal Pharma Limited  " ,
" Murudeshwar Ceramics Limited  " ,
" DCM Nouvelle Limited  " ,
" CL Educate Limited  " ,
" Wanbury Limited " ,
" Shyam Century Ferrous Limited " ,
" Sumit Woods Limited " ,
" Ginni Filaments Limited " ,
" Pioneer Embroideries Limited  " ,
" JMT Auto Limited  " ,
" Birla Tyres Limited " ,
" Gillanders Arbuthnot & Company Limited  " ,
" Hindprakash Industries Limited  " ,
" Manaksia Steels Limited " ,
" Vera Synthetic Limited  " ,
" Vaishali Pharma Limited " ,
" GPT Infraprojects Limited " ,
" Univastu India Limited  " ,
" Omax Autos Limited  " ,
" Ashima Limited  " ,
" Sintex Plastics Technology Limited  " ,
" Kamat Hotels (I) Limited  " ,
" Weizmann Limited  " ,
" Premier Polyfilm Limited  " ,
" Mukta Arts Limited  " ,
" Penta Gold Limited  " ,
" LGB Forge Limited " ,
" Naga Dhunseri Group Limited " ,
" Bigbloc Construction Limited  " ,
" Damodar Industries Limited  " ,
" Pansari Developers Limited  " ,
" Rajshree Sugars & Chemicals Limited " ,
" IL&FS Transportation Networks Limited " ,
" Almondz Global Securities Limited " ,
" Sonam Clock Limited " ,
" Mcnally Bharat Engineering Company Limited  " ,
" Sintex Industries Limited " ,
" Beta Drugs Limited  " ,
" Indian Card Clothing Company Limited  " ,
" Malu Paper Mills Limited  " ,
" Brooks Laboratories Limited " ,
" Maral Overseas Limited  " ,
" Sical Logistics Limited " ,
" Shaival Reality Limited " ,
" Tainwala Chemical and Plastic (I) Limited " ,
" Ruchi Infrastructure Limited  " ,
" Supreme Engineering Limited " ,
" The Western India Plywoods Limited  " ,
" Dev Information Technology Limited  " ,
" Mindteck (India) Limited  " ,
" Reliance Home Finance Limited " ,
" Softtech Engineers Limited  " ,
" Websol Energy System Limited  " ,
" Ausom Enterprise Limited  " ,
" ISMT Limited  " ,
" Lyka Labs Limited " ,
" Sicagen India Limited " ,
" B.A.G Films and Media Limited " ,
" Hexa Tradex Limited " ,
" The Byke Hospitality Ltd  " ,
" ShreeOswal Seeds And Chemicals Limited  " ,
" Rolta India Limited " ,
" Golden Tobacco Limited  " ,
" IVP Limited " ,
" Macpower CNC Machines Limited " ,
" Marvel Decor Limited  " ,
" Archidply Industries Limited  " ,
" VIP Clothing Limited  " ,
" Khfm Hospitality And Facility Management Services Limited " ,
" JHS Svendgaard Laboratories Limited " ,
" Aakash Exploration Services Limited " ,
" South West Pinnacle Exploration Limited " ,
" Vinny Overseas Limited  " ,
" Prajay Engineers Syndicate Limited  " ,
" One Point One Solutions Limited " ,
" kwality limited " ,
" Surana Telecom and Power Limited  " ,
" GSS Infotech Limited  " ,
" Bedmutha Industries Limited " ,
" Intense Technologies Limited  " ,
" Kalyani Forge Limited " ,
" Art Nirman Limited  " ,
" Aurangabad Distillery Limited " ,
" Rama Steel Tubes Limited  " ,
" Cords Cable Industries Limited  " ,
" Lloyds Steels Industries Limited  " ,
" Aarvi Encon Limited " ,
" Visa Steel Limited  " ,
" Ambani Organics Limited " ,
" AVG Logistics Limited " ,
" Pressman Advertising Limited  " ,
" Intrasoft Technologies Limited  " ,
" Vikas EcoTech Limited " ,
" Salasar Exteriors and Contour Limited " ,
" R. S. Software (India) Limited  " ,
" The Grob Tea Company Limited  " ,
" CMI Limited " ,
" Sundaram Multi Pap Limited  " ,
" M K Proteins Limited  " ,
" Remsons Industries Limited  " ,
" Archies Limited " ,
" OCL Iron and Steel Limited  " ,
" Country Club Hospitality & Holidays Limited " ,
" Alpa Laboratories Limited " ,
" HOV Services Limited  " ,
" Aro Granite Industries Limited  " ,
" Punj Lloyd Limited  " ,
" Compucom Software Limited " ,
" Cimmco Limited  " ,
" MBL Infrastructures Limited " ,
" Moksh Ornaments Limited " ,
" Morarjee Textiles Limited " ,
" Cinevista Limited " ,
" Tirupati Forge Limited  " ,
" Rollatainers Limited  " ,
" Cambridge Technology Enterprises Limited  " ,
" Lokesh Machines Limited " ,
" Total Transport Systems Limited " ,
" Venus Remedies Limited  " ,
" Ascom Leasing & Investments Limited " ,
" Steel City Securities Limited " ,
" Silgo Retail Limited  " ,
" Opal Luxury Time Products Limited " ,
" Reliable Data Services Limited  " ,
" Surana Solar Limited  " ,
" Autoline Industries Limited " ,
" Globe Textiles (India) Limited  " ,
" Arvee Laboratories (India) Limited  " ,
" Precot Meridian Limited " ,
" Silly Monks Entertainment Limited " ,
" Ducon Infratechnologies Limited " ,
" FCS Software Solutions Limited  " ,
" Tarmat Limited  " ,
" Alkali Metals Limited " ,
" Sarveshwar Foods Limited  " ,
" Priti International Limited " ,
" DCM  Limited  " ,
" DB (International) Stock Brokers Limited  " ,
" Digicontent Limited " ,
" Goldstar Power Limited  " ,
" Banka BioLoo Limited  " ,
" Suryalakshmi Cotton Mills Limited " ,
" HEC Infra Projects Limited  " ,
" Sambhaav Media Limited  " ,
" Radha Madhav Corporation Limited  " ,
" Bharat Gears Limited  " ,
" Airo Lam limited  " ,
" Gammon Infrastructure Projects Limited  " ,
" DC Infotech and Communication Limited " ,
" Megasoft Limited  " ,
" Shree Tirupati Balajee FIBC Limited " ,
" IL&FS Engineering and Construction Company Limited  " ,
" ARSS Infrastructure Projects Limited  " ,
" Sona Hi Sona Jewellers (Gujarat) Limited  " ,
" Continental Seeds and Chemicals Limited " ,
" Hisar Metal Industries Limited  " ,
" Shradha Infraprojects Limited " ,
" Atlanta  Limited  " ,
" Indbank Merchant Banking Services Limited " ,
" Manugraph India Limited " ,
" Garden Silk Mills Limited " ,
" Akg Exim Limited  " ,
" Pearl Polymers Limited  " ,
" Shree Rama Multi-Tech Limited " ,
" Godha Cabcon & Insulation Limited " ,
" Next Mediaworks Limited " ,
" Supreme Infrastructure India Limited  " ,
" Texmo Pipes and Products Limited  " ,
" Aaron Industries Limited  " ,
" Ganges Securities Limited " ,
" Adlabs Entertainment Limited  " ,
" Kohinoor Foods Limited  " ,
" The Peria Karamalai Tea & Produce Company Limited " ,
" Keynote Financial Services Limited  " ,
" Brand Concepts Limited  " ,
" Mcleod Russel India Limited " ,
" KSS Limited " ,
" Mohini Health & Hygiene Limited " ,
" Focus Lighting and Fixtures Limited " ,
" Accuracy Shipping Limited " ,
" Sanghvi Forging and Engineering Limited " ,
" Automotive Stampings and Assemblies Limited " ,
" Shubhlaxmi Jewel Art Limited  " ,
" Keerti Knowledge and Skills Limited " ,
" Energy Development Company Limited  " ,
" Karuturi Global Limited " ,
" AMD Industries Limited  " ,
" Dharani Sugars & Chemicals Limited  " ,
" MIG Media Neurons Limited " ,
" Surevin BPO Services Limited  " ,
" Gyscoal Alloys Limited  " ,
" Nila Spaces Limited " ,
" E2E Networks Limited  " ,
" Banaras Beads Limited " ,
" Kshitij Polyline Limited  " ,
" Bright Solar Limited  " ,
" Par Drugs and Chemicals Limited " ,
" Salona Cotspin Limited  " ,
" AVSL Industries Limited " ,
" Atlas Cycles (Haryana) Limited  " ,
" BSL Limited " ,
" Beardsell Limited " ,
" Shiva Mills Limited " ,
" Maan Aluminium Limited  " ,
" SPML Infra Limited  " ,
" Xpro India Limited  " ,
" Surani Steel Tubes Limited  " ,
" Lambodhara Textiles Limited " ,
" Aarvee Denims & Exports Limited " ,
" Indosolar Limited " ,
" Palash Securities Limited " ,
" Anik Industries Limited " ,
" Celebrity Fashions Limited  " ,
" Mercator Limited  " ,
" GTL Limited " ,
" North Eastern Carrying Corporation Limited  " ,
" Simbhaoli Sugars Limited  " ,
" Delta Manufacturing Limited " ,
" Ushanti Colour Chem Limited " ,
" Patel Integrated Logistics Limited  " ,
" Servotech Power Systems Limited " ,
" Zenith Exports Limited  " ,
" McDowell Holdings Limited " ,
" Manaksia Aluminium Company Limited  " ,
" ANI Integrated Services Limited " ,
" AVRO INDIA LIMITED  " ,
" BLB Limited " ,
" Tera Software Limited " ,
" Madhav Marbles and Granites Limited " ,
" Metalyst Forgings Limited " ,
" Shirpur Gold Refinery Limited " ,
" Barak Valley Cements Limited  " ,
" Kernex Microsystems (India) Limited " ,
" Shanti Overseas (India) Limited " ,
" Ansal Housing Limited " ,
" Latteys Industries Limited  " ,
" Manaksia Coated Metals & Industries Limited " ,
" Rajnandini Metal Limited  " ,
" Indowind Energy Limited " ,
" Globe International Carriers Limited  " ,
" Artedz Fabs Limited " ,
" Narmada Agrobase Limited  " ,
" Khandwala Securities Limited  " ,
" ABM International Limited " ,
" Bang Overseas Limited " ,
" STL Global Limited  " ,
" Oriental Trimex Limited " ,
" S.A.L. Steel Limited  " ,
" Shri Ram Switchgears Limited  " ,
" Fourth Dimension Solutions Limited  " ,
" SEL Manufacturing Company Limited " ,
" KSK Energy Ventures Limited " ,
" IZMO Limited  " ,
" Goldstone Technologies Limited  " ,
" S.S. Infrastructure Development Consultants Limited " ,
" KKV Agro Powers Limited " ,
" Milton Industries Limited " ,
" Uniinfo Telecom Services Limited  " ,
" Jet Freight Logistics Limited " ,
" Jyoti Structures Limited  " ,
" CIL Nova Petrochemicals Limited " ,
" Oil Country Tubular Limited " ,
" Prolife Industries Limited  " ,
" Aventus Buildcon Limited  " ,
" Indo Thai Securities Limited  " ,
" Dynacons Systems & Solutions Limited  " ,
" Ahimsa Industries Limited " ,
" Century Extrusions Limited  " ,
" Tree House Education & Accessories Limited  " ,
" Global Education Limited  " ,
" Lagnam Spintex Limited  " ,
" Cadsys (India) Limited  " ,
" Mangalam Timber Products Limited  " ,
" The Mandhana Retail Ventures Limited  " ,
" NRB Industrial Bearings Limited " ,
" Sumeet Industries Limited " ,
" R M Drip and Sprinklers Systems Limited " ,
" Karma Energy Limited  " ,
" Autolite (India) Limited  " ,
" Infomedia Press Limited " ,
" Ultra Wiring Connectivity System Limited  " ,
" Times Guaranty Limited  " ,
" Perfect Infraengineers Limited  " ,
" Kanani Industries Limited " ,
" Cubex Tubings Limited " ,
" Biofil Chemicals & Pharmaceuticals Limited  " ,
" Laxmi Cotspin Limited " ,
" Marshall Machines Limited " ,
" Vaxtex Cotfab Limited " ,
" Magnum Ventures Limited " ,
" Lakshmi Finance & Industrial Corporation Limited  " ,
" Zodiac JRD- MKJ Limited " ,
" Ortin Laboratories Limited  " ,
" Madhucon Projects Limited " ,
" Agri-Tech (India) Limited " ,
" Eon Electric Limited  " ,
" Ind-Swift Limited " ,
" Educomp Solutions Limited " ,
" Agro Phos India Limited " ,
" Super Spinning Mills Limited  " ,
" Somi Conveyor Beltings Limited  " ,
" A B Infrabuild Limited  " ,
" SKS Textiles Limited  " ,
" Landmark Property Development Company Limited " ,
" Kridhan Infra Limited " ,
" Castex Technologies Limited " ,
" 21st Century Management Services Limited  " ,
" Innovative Tyres and Tubes Limited  " ,
" Hindcon Chemicals Limited " ,
" Tijaria Polypipes Limited " ,
" Lexus Granito (India) Limited " ,
" Bhandari Hosiery Exports Limited  " ,
" CKP Products Limited  " ,
" Williamson Magor & Company Limited  " ,
" Pritish Nandy Communications Limited  " ,
" Adroit Infotech Limited " ,
" Sikko Industries Limited  " ,
" Nagreeka Exports Limited  " ,
" Bil Energy Systems Limited  " ,
" Ravi Kumar Distilleries Limited " ,
" Nitin Fire Protection Industries Limited  " ,
" Powerful Technologies Limited " ,
" Jet Knitwears Limited " ,
" Shah Alloys Limited " ,
" Consolidated Construction Consortium Limited  " ,
" MIC Electronics Limited " ,
" Ace Integrated Solutions Limited  " ,
" Cox & Kings Limited " ,
" Palred Technologies Limited " ,
" Solex Energy Limited  " ,
" California Software Company Limited " ,
" SecUR Credentials Limited " ,
" Arihant Foundations & Housing Limited " ,
" Diamond Power Infra Ltd " ,
" Ganga Forging Limited " ,
" STI India Limited " ,
" CMM Infraprojects Limited " ,
" Arcotech Limited  " ,
" GTN Industries Limited  " ,
" Crown Lifters Limited " ,
" Hilton Metal Forging Limited  " ,
" Mukand Engineers Limited  " ,
" S&S Power Switchgears Limited " ,
" JITF Infralogistics Limited " ,
" Excel Realty N Infra Limited  " ,
" Zodiac Energy Limited " ,
" A B N Intercorp Limited " ,
" Balkrishna Paper Mills Limited  " ,
" IMP Powers Limited  " ,
" ASL Industries Limited  " ,
" Jindal Photo Limited  " ,
" Vadivarhe Speciality Chemicals Limited  " ,
" Flexituff Ventures International Limited  " ,
" Stampede Capital Limited  " ,
" DQ Entertainment (International) Limited  " ,
" Goenka Diamond and Jewels Limited " ,
" Lypsa Gems & Jewellery Limited  " ,
" Nandani Creation Limited  " ,
" Madhya Pradesh Today Media Limited  " ,
" Jindal Poly Investment and Finance Company Limited  " ,
" Vardhman Polytex Limited  " ,
" Digjam Limited  " ,
" Patspin India Limited " ,
" Vaswani Industries Limited  " ,
" Shyam Telecom Limited " ,
" Sanco Industries Limited  " ,
" Parabolic Drugs Limited " ,
" Eurotex Industries and Exports Limited  " ,
" Global Offshore Services Limited  " ,
" Sri Havisha Hospitality and Infrastructure Limited  " ,
" Shekhawati Poly-Yarn Limited  " ,
" TREJHARA SOLUTIONS LIMITED  " ,
" Jalan Transolutions (India) Limited " ,
" Niraj Ispat Industries Limited  " ,
" S.E. Power Limited  " ,
" GTN Textiles Limited  " ,
" Husys Consulting Limited  " ,
" 3P Land Holdings Limited  " ,
" Sathavahana Ispat Limited " ,
" TGB Banquets And Hotels Limited " ,
" Mohota Industries Limited " ,
" Felix Industries Limited  " ,
" BSEL Infrastructure Realty Limited  " ,
" Soma Textiles & Industries Limited  " ,
" Burnpur Cement Limited  " ,
" Pulz Electronics Limited  " ,
" Gayatri Highways Limited  " ,
" Power & Instrumentation (Gujarat) Limited " ,
" Kalyani Commercials Limited " ,
" Radaan Mediaworks India Limited " ,
" NK Industries Limited " ,
" Visagar Polytex Limited " ,
" Country Condo's Limited " ,
" Ankit Metal & Power Limited " ,
" TCI Finance Limited " ,
" Eastern Silk Industries Limited " ,
" Blue Coast Hotels Limited " ,
" National Steel And Agro Industries Limited  " ,
" Easun Reyrolle Limited  " ,
" Sezal Glass Limited " ,
" A and M Jumbo Bags Limited  " ,
" Empee Distilleries Limited  " ,
" Transwarranty Finance Limited " ,
" Dhanuka Realty Limited  " ,
" Mindpool Technologies Limited " ,
" Nagreeka Capital & Infrastructure Limited " ,
" Omkar Speciality Chemicals Limited  " ,
" Setubandhan Infrastructure Limited  " ,
" Mohit Industries Limited  " ,
" Onelife Capital Advisors Limited  " ,
" Technofab Engineering Limited " ,
" Bhalchandram Clothing Limited " ,
" Ajooni Biotech Limited  " ,
" United Polyfab Gujarat Limited  " ,
" Pushpanjali Realms and Infratech Limited  " ,
" Splendid Metal Products Limited " ,
" Accord Synergy Limited  " ,
" Grand Foundry Limited " ,
" Spacenet Enterprises India Limited  " ,
" Sri Adhikari Brothers Television Network Limited  " ,
" HB Stockholdings Limited  " ,
" CKP Leisure Limited " ,
" JVL Agro Industries Limited " ,
" Norben Tea & Exports Limited  " ,
" Mask Investments Limited  " ,
" Gujarat Raffia Industries Limited " ,
" Rohit Ferro-Tech Limited  " ,
" Premier Limited " ,
" Zenith Birla (India) Limited  " ,
" Rajdarshan Industries Limited " ,
" Zicom Electronic Security Systems Limited " ,
" Gujarat Lease Financing Limited " ,
" PSL Limited " ,
" Vasa Retail and Overseas Ltd  " ,
" Debock Sales And Marketing Limited  " ,
" TV Vision Limited " ,
" Chromatic India Limited " ,
" Diligent Media Corporation Limited  " ,
" SMVD Poly Pack Limited  " ,
" Thiru Arooran Sugars Limited  " ,
" W S Industries (I) Limited  " ,
" Omfurn India Limited  " ,
" Talwalkars Better Value Fitness Limited " ,
" Manav Infra Projects Limited  " ,
" Viceroy Hotels Limited  " ,
" Bafna Pharmaceuticals Limited " ,
" Melstar Information Technologies Limited  " ,
" Impex Ferro Tech Limited  " ,
" Emco Limited  " ,
" Creative Eye Limited  " ,
" Alps Industries Limited " ,
" Techindia Nirman Limited  " ,
" C & C Constructions Limited " ,
" Tamilnadu Telecommunication Limited " ,
" Prakash Steelage Limited  " ,
" Bkm Industries Limited  " ,
" Sujana Universal Industries Limited " ,
" Soni Soya Products Limited  " ,
" Talwalkars Healthclubs Limited  " ,
" Unity Infraprojects Limited " ,
" Proseed India Limited " ,
" Usha Martin Education & Solutions Limited " ,
" Transwind Infrastructures Limited " ,
" Bartronics India Limited  " ,
" Syncom Healthcare Limited " ,
" Gretex Industries Limited " ,
" Cox & Kings Financial Service Limited " ,
" Viji Finance Limited  " ,
" Integra Garments and Textiles Limited " ,
" PAE Limited " ,
" International Constructions Limited " ,
" Spentex Industries Limited  " ,
" Metkore Alloys & Industries Limited " ,
" Raj Rayon Industries Limited  " ,
" GI Engineering Solutions Limited  " ,
" Neueon Towers Limited " ,
" Pradip Overseas Limited " ,
" Alchemist Limited " ,
" Ortel Communications Limited  " ,
" Hotel Rugby Limited " ,
" JIK Industries Limited  " ,
" Kaushalya Infrastructure Development Corporation Limited  " ,
" Lakshmi Precision Screws Limited  " ,
" Thomas Scott (India) Limited  " ,
" GB Global Limited " ,
" Euro Ceramics Limited " ,
" Ramsarup Industries Limited " ,
" Bohra Industries Limited  " ,
" Euro Multivision Limited  " ,
" Jain Studios Limited  " ,
" DCM Financial Services Limited  " ,
" Jaihind Projects Limited  " ,
" Blue Chip India Limited " ,
" Sab Events & Governance Now Media Limited " ,
" ATN International Limited " ,
" Amit Spinning Industries Limited  " ,
" Orchid Pharma Limited " ,
" Raj Oil Mills Limited " ,
" Sharon Bio-Medicine Limited " ,
" Tantia Constructions Limited  " ,
];
